Traceback (most recent call last):
  File "/home/runner/.cache/pypoetry/virtualenvs/customer-base-analysis-F-W2gxNr-py3.10/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/runner/.cache/pypoetry/virtualenvs/customer-base-analysis-F-W2gxNr-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/runner/.cache/pypoetry/virtualenvs/customer-base-analysis-F-W2gxNr-py3.10/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/runner/.cache/pypoetry/virtualenvs/customer-base-analysis-F-W2gxNr-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/runner/.cache/pypoetry/virtualenvs/customer-base-analysis-F-W2gxNr-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/.cache/pypoetry/virtualenvs/customer-base-analysis-F-W2gxNr-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
group_by_reshape = np.reshape(group_by, (3, 4))
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn[15], line 1[0m
[0;32m----> 1[0m group_by_reshape [38;5;241m=[39m [43mnp[49m[38;5;241;43m.[39;49m[43mreshape[49m[43m([49m[43mgroup_by[49m[43m,[49m[43m [49m[43m([49m[38;5;241;43m3[39;49m[43m,[49m[43m [49m[38;5;241;43m4[39;49m[43m)[49m[43m)[49m

File [0;32m~/.cache/pypoetry/virtualenvs/customer-base-analysis-F-W2gxNr-py3.10/lib/python3.10/site-packages/numpy/core/fromnumeric.py:285[0m, in [0;36mreshape[0;34m(a, newshape, order)[0m
[1;32m    200[0m [38;5;129m@array_function_dispatch[39m(_reshape_dispatcher)
[1;32m    201[0m [38;5;28;01mdef[39;00m [38;5;21mreshape[39m(a, newshape, order[38;5;241m=[39m[38;5;124m'[39m[38;5;124mC[39m[38;5;124m'[39m):
[1;32m    202[0m [38;5;250m    [39m[38;5;124;03m"""[39;00m
[1;32m    203[0m [38;5;124;03m    Gives a new shape to an array without changing its data.[39;00m
[1;32m    204[0m 
[0;32m   (...)[0m
[1;32m    283[0m [38;5;124;03m           [5, 6]])[39;00m
[1;32m    284[0m [38;5;124;03m    """[39;00m
[0;32m--> 285[0m     [38;5;28;01mreturn[39;00m [43m_wrapfunc[49m[43m([49m[43ma[49m[43m,[49m[43m [49m[38;5;124;43m'[39;49m[38;5;124;43mreshape[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[43mnewshape[49m[43m,[49m[43m [49m[43morder[49m[38;5;241;43m=[39;49m[43morder[49m[43m)[49m

File [0;32m~/.cache/pypoetry/virtualenvs/customer-base-analysis-F-W2gxNr-py3.10/lib/python3.10/site-packages/numpy/core/fromnumeric.py:56[0m, in [0;36m_wrapfunc[0;34m(obj, method, *args, **kwds)[0m
[1;32m     54[0m bound [38;5;241m=[39m [38;5;28mgetattr[39m(obj, method, [38;5;28;01mNone[39;00m)
[1;32m     55[0m [38;5;28;01mif[39;00m bound [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[0;32m---> 56[0m     [38;5;28;01mreturn[39;00m [43m_wrapit[49m[43m([49m[43mobj[49m[43m,[49m[43m [49m[43mmethod[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[43margs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwds[49m[43m)[49m
[1;32m     58[0m [38;5;28;01mtry[39;00m:
[1;32m     59[0m     [38;5;28;01mreturn[39;00m bound([38;5;241m*[39margs, [38;5;241m*[39m[38;5;241m*[39mkwds)

File [0;32m~/.cache/pypoetry/virtualenvs/customer-base-analysis-F-W2gxNr-py3.10/lib/python3.10/site-packages/numpy/core/fromnumeric.py:45[0m, in [0;36m_wrapit[0;34m(obj, method, *args, **kwds)[0m
[1;32m     43[0m [38;5;28;01mexcept[39;00m [38;5;167;01mAttributeError[39;00m:
[1;32m     44[0m     wrap [38;5;241m=[39m [38;5;28;01mNone[39;00m
[0;32m---> 45[0m result [38;5;241m=[39m [38;5;28mgetattr[39m([43masarray[49m[43m([49m[43mobj[49m[43m)[49m, method)([38;5;241m*[39margs, [38;5;241m*[39m[38;5;241m*[39mkwds)
[1;32m     46[0m [38;5;28;01mif[39;00m wrap:
[1;32m     47[0m     [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m [38;5;28misinstance[39m(result, mu[38;5;241m.[39mndarray):

[0;31mValueError[0m: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (12,) + inhomogeneous part.

